#!/bin/sh

# start dhcpd. not going to expose the args for this, since they shouldn't really change
start_dhcpd () {
	/usr/sbin/dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf &
	DHCPD_PID=$!
}

kill_dhcpd () {
	[ $DHCP_PID ] && kill $DHCPD_PID
}

check_conf () {
	echo "$SHASUM" | sha1sum -c -
	SAME=$?
	if [ $SAME -ne 0 ]; then
		echo "hostlist changed, restarting dhcp server"
		SHASUM=$(sha1sum /etc/dhcp/conf.d/hostlist)
		kill_dhcpd
		start_dhcpd
	else
		echo "No changes made to hostlist, continuing"
	fi
}

if [ "x$IP" == "x" ]; then
	ip route get $DNS > /tmp/net
	read t t gw t t t IP < /tmp/net
	subn=$(echo $IP | cut -f 1-3 -d .)
else
	subn=$(echo $IP | cut -f 1-3 -d .)
	gw=$subn".1"
fi
bcast=$subn".255"
subn=$subn".0"

cat << EOF > /etc/dhcp/dhcpd.conf
default-lease-time 600;
allow booting;
allow bootp;
log-facility local7;
subnet $subn netmask 255.255.255.0 {
	option routers $gw;
	option subnet-mask 255.255.255.0;
	option domain-name-servers $DNS;
	option broadcast-address $bcast;
	next-server $IP;
	filename "netboot.xyz.kpxe";
}
EOF

[ -f /etc/dhcp/conf.d/hostlist ] || touch /etc/dhcp/conf.d/hostlist

while [ 1 ]
do
	check_conf
	sleep $DHCP_update_time
done
